[dev]
  publish = "_site"
  command = "npm run dev"

[build]
  command = "npm run build"
  functions = "src/_functions/"
  edge_functions = "src/_edge-functions/"

[[edge_functions]]
  path = "/blog/*"
  function = "referer"

[[edge_functions]]
  path = "/"
  function = "twitch"

[[edge_functions]]
  path = "/about"
  function = "clean-up-past-events"

[[edge_functions]]
  path = "/about"
  function = "localize-time"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/projects"
  to = "https://github.com/whitep4nth3r?tab=repositories"
  status = 301

[[redirects]]
  from = "/topics"
  to = "/topics/webdev/"
  status = 308

[[redirects]]
  from = "/faqs"
  to = "/blog/faqs/"
  status = 301

[[redirects]]
  from = "/github"
  to = "https://github.com/whitep4nth3r"
  status = 301

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/GQbXUVCneJ"
  status = 301

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://indieweb.social/.well-known/webfinger?resource=acct:whitep4nth3r@indieweb.social"
  status = 200

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    include = ["GOOGLE_PRIVATE_KEY"]
